backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: /img

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/markdown-pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: &title "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "path", name: src/*title, widget: "hidden", }
      - {label: "title", name: "title", widget: "string"}
      - {label: "date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
